### ISSUE TITLE
No ”data" folder

### ISSUE THREAD

**Issue by weiyitao1995** [bzdfzfer/CloudLine2Plane#1]
would you please provide some sample data for test. I did not found the "data" folder in this repo. Thanks in advance

**Comment by bzdfzfer** [comment]
sure, i will upload some data with google drive.

**Comment by Jueqian** [comment]
Is the data file available now?

**Comment by bzdfzfer** [comment]
Sure, sorry for the late update, i will upload them this weekend.

**Comment by bzdfzfer** [comment]
The data is now available at: https://drive.google.com/file/d/1Qqw_p5DxROCsCECSu5KzPagH9PgvyQ8b/view?usp=sharing
